"""Ports the control context relies on; adapters live in infrastructure."""
from typing import Protocol


class ServoDriver(Protocol):
    """Commands in PCA9685 counts, never position feedback; construction accesses no hardware."""
    scope: str  # 'synthetic', 'commissioning' or 'validated'; must match the limits' scope.

    def prepare(self) -> None: ...
    def write(self, channel: int, count: int) -> None: ...
    def disable(self, channel: int) -> None: ...
    def verify_off(self) -> None: ...
    def close(self) -> None: ...


class PoseRepository(Protocol):
    """Observed PARK/HOME command definitions for one driver scope."""
    scope: str

    def load(self, name: str) -> dict[int, int] | None: ...
    def save(self, name: str, counts: dict[int, int], *, provenance: str) -> str: ...


class DemoRepository(Protocol):
    """Immutable named sequences of recorded positions for one driver scope."""
    scope: str

    def save(self, name: str, positions: list[dict]) -> str: ...
    def load(self, filename: str) -> dict: ...
    def saved(self) -> list[dict]: ...
